datagrids:
    orcrm-contact-requests-grid:
        extended_entity_name: 'Oro\Bundle\ContactUsBundle\Entity\ContactRequest'
        acl_resource: oro_contactus_request_view
        source:
            type: orm
            query:
                select:
                    - cr.id
                    - cr.firstName
                    - cr.lastName
                    - cr.emailAddress
                    - cr.phone
                    - cr.createdAt
                from:
                    - { table: 'Oro\Bundle\ContactUsBundle\Entity\ContactRequest', alias: cr }
                join:
                    left:
                        - { join: cr.contactReason, alias: rsn }
        columns:
            firstName:
                label:         oro.contactus.contactrequest.first_name.label
            lastName:
                label:         oro.contactus.contactrequest.last_name.label
            phone:
                label:         oro.contactus.contactrequest.phone.label
                frontend_type: phone
            emailAddress:
                label:         oro.contactus.contactrequest.email_address.label
                cellClassName: 'direction-ltr'
            createdAt:
                frontend_type: datetime
                label:         oro.ui.created_at
            cntReason:
                label:         oro.contactus.contactreason.entity_label
        sorters:
            columns:
                firstName:
                    data_name: cr.firstName
                lastName:
                    data_name: cr.lastName
                phone:
                    data_name: cr.phone
                emailAddress:
                    data_name: cr.emailAddress
                createdAt:
                    data_name: cr.createdAt
            default:
                createdAt: DESC
        filters:
            columns:
                firstName:
                    type:      string
                    data_name: cr.firstName
                lastName:
                    type:      string
                    data_name: cr.lastName
                phone:
                    type:      string
                    data_name: cr.phone
                emailAddress:
                    type:      string
                    data_name: cr.emailAddress
                createdAt:
                    type:      datetime
                    data_name: cr.createdAt
                cntReason:
                    type:      string
                    data_name: cntReason
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_contactus_request_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_contactus_request_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_contactus_request_delete
                params:     [ id ]
            cntReason:
                type:        localized_value
                data_name:   rsn.titles
                allow_empty: true
        actions:
            view:
                acl_resource: oro_contactus_request_view
                type:         navigate
                label:        oro.grid.action.view
                icon:         eye
                link:         view_link
                rowAction:    true
            update:
                acl_resource: oro_contactus_request_edit
                type:         navigate
                label:        oro.grid.action.update
                icon:         edit
                link:         update_link
            delete:
                acl_resource: oro_contactus_request_delete
                type:         delete
                label:        oro.grid.action.delete
                icon:         trash
                link:         delete_link
        options:
            entityHint: oro.contactus.contactrequest.entity_plural_label
            entity_pagination: true

    orcrm-contact-reasons-grid:
        extended_entity_name: 'Oro\Bundle\ContactUsBundle\Entity\ContactReason'
        acl_resource: oro_contactus_reason_view
        options:
            entity_pagination: true
        source:
            type:         orm
            query:
                select:
                    - contactReason.id
                from:
                    - { table: Oro\Bundle\ContactUsBundle\Entity\ContactReason, alias: contactReason }
                where:
                    and:
                        - contactReason.deletedAt IS NULL
        columns:
            title:
                label: oro.contactus.contactreason.label.label
        sorters:
            columns:
                title:
                    data_name: title
        filters:
            columns:
                title:
                    type:      string
                    data_name: title
        properties:
            id: ~
            update_link:
                type:   url
                route:  oro_contactus_reason_update
                params: [ id ]
            delete_link:
                type:   url
                route:  oro_contactus_reason_delete
                params: [ id ]
            title:
                type: localized_value
                data_name: titles
        actions:
            update:
                acl_resource: oro_contactus_reason_update
                type:         navigate
                label:        oro.grid.action.update
                icon:         edit
                link:         update_link
                rowAction:    true
            delete:
                acl_resource: oro_contactus_reason_delete
                type:         delete
                label:        oro.grid.action.delete
                icon:         trash
                link:         delete_link
