entity_config:
    customer:
        # You can find out more about attributes in the documentation: https://doc.oroinc.com/backend/configuration/annotation/config/#customer
        entity:
            items:
                enabled:
                associated_opportunity_block_priority:
